name: my_project
description: A sample example for package testing.
version: 1.0.0

environment:
  sdk: ^3.4.4

dependencies:
  s2geometry_dart: ^0.0.1
    path: package/s2geometry_dart


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  
