name: s2geometry_dart
description: A Dart port of the S2 Geometry Library from JavaScript, providing utilities for geographic calculations and conversions.
version: 0.0.1
repository: https://github.com/h102136/s2geometry_dart

environment:
  sdk: ^3.4.4

dependencies:
  test: ^1.20.1
  coverage: ^1.9.0
  fixnum: ^1.1.0
  

dev_dependencies:
  lints: ^3.0.0

publish_to: 'https://pub.dev'
